import{S as q,a as B,i as a}from"./assets/vendor-GN5hr8qZ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),p=document.querySelector(".load-more");let M=new q(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const t=o.map(({webformatURL:s,largeImageURL:n,tags:e,likes:r,views:i,comments:v,downloads:S})=>`
      <li class="gallery-item">
        <a href="${n}">
          <img src="${s}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r}</p>
          <p><b>Views:</b> ${i}</p>
          <p><b>Comments:</b> ${v}</p>
          <p><b>Downloads:</b> ${S}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",t),M.refresh()}function $(){f.innerHTML=""}function h(){m.classList.remove("hidden")}function g(){m.classList.add("hidden")}function L(){p.classList.remove("hidden")}function b(){p.classList.add("hidden")}function P(){const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}const E="51715222-245823a157b91ecf18a5e059a",O="https://pixabay.com/api/";async function w(o,t=1,s=15){const n={key:E,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:s};return(await B.get(O,{params:n})).data}const u=document.querySelector(".form"),H=document.querySelector(".load-more");let c="",l=1;const d=15;u.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.currentTarget.elements.query.value.trim(),!c){a.warning({title:"Увага",message:"Введіть пошуковий запит!"});return}l=1,$(),b();try{h();const t=await w(c,l,d);if(t.hits.length===0){a.info({title:"Немає результатів",message:"Зображення за цим запитом не знайдено."});return}y(t.hits),t.totalHits>d&&L()}catch(t){a.error({title:"Помилка",message:"Не вдалося завантажити зображення. Спробуйте пізніше."}),console.error(t)}finally{g(),u.reset()}});H.addEventListener("click",async()=>{l+=1,b();try{h();const o=await w(c,l,d);y(o.hits),P();const t=Math.ceil(o.totalHits/d);l<t?L():a.info({title:"Кінець результатів",message:"Ви переглянули всі знайдені зображення."})}catch(o){a.error({title:"Помилка",message:"Не вдалося завантажити більше зображень."}),console.error(o)}finally{g()}});
//# sourceMappingURL=index.js.map
